- name: Create photos mount path
  file:
    path: /mnt/photos
    state: directory

- name: Mount network share for photos
  lineinfile:
    path: /etc/fstab
    line: "{{ nas_host }}:/mnt/Data/Photos		/mnt/photos	nfs rw,user,auto, 0 0"
    state: present
    
- name: Get Photoprism docker-compose template
  set_fact:
    docker_compose_path: "{{ role_path }}/templates/docker-compose.j2"

- name: Install Photoprism
  include_role:
    name: portainer_stack
  vars:
    template_path: "{{ docker_compose_path }}"
    portainer_host: "{{ ansible_host }}"
    user: "{{ portainer_user }}"
    password: "{{ portainer_password }}"
    local_endpoint: "{{ inventory_hostname }}"
    stack_name: photoprism
