- name: Get Jellyfin docker-compose template
  set_fact:
    docker_compose_path: "{{ role_path }}/templates/docker-compose.j2"

- name: Install Jellyfin
  include_role:
    name: portainer_stack
  vars:
    template_path: "{{ docker_compose_path }}"
    portainer_host: "{{ ansible_host }}"
    user: "{{ portainer_user }}"
    password: "{{ portainer_password }}"
    local_endpoint: "{{ inventory_hostname }}"
    stack_name: jellyfin    

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ username }}/jellyfin"
    - "/home/{{ username }}/jellyfin/config"
    - "/home/{{ username }}/jellyfin/cache"

- name: Change ownership of Jellyfin directory
  file:
    path: "/home/{{ username }}/jellyfin"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Register Jellyfin with Traefik
  template:
    src: "{{ role_path }}/templates/jellyfin.j2"
    dest: "/home/{{ username }}/traefik/config/jellyfin.yml"
  