- hosts: all
  become: yes
  roles:
    - name: Install system dependencies
      role: system
    - name: Add containers management
      role: containers

- hosts: main
  become: yes
  roles:
    - role: galaxy.swap # Increase swapfile size
    - role: portainer
    - role: traefik
    - role: authelia
    - role: pihole
    - role: photoprism
    - role: jackett
    - role: jellyfin
    - role: lidarr
    - role: home_assistant
    