---
- hosts: all
  become: yes
  roles:
    - role: system
    - role: containers
    
- hosts: main
  become: yes
  roles:
    - role: infrastructure

- hosts: nodes
  become: yes
  roles:
    - role: nodes
    - role: galaxy.swap
