- name: Create mount paths
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /mnt/music

- name: Mount network share for music
  lineinfile:
    path: /etc/fstab
    line: "{{ nas_host }}:/mnt/Data/Musik		/mnt/music	nfs rw,user,auto, 0 0"
    state: present
