- name: Create Portainer data volume
  community.docker.docker_volume:
    name: portainer_data

- name: Run Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    detach: true
    restart_policy: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
