- name: Build traefik stack YAML
  set_fact:
    traefik_yaml_contents: "{{ lookup('template', '{{ role_path}}/templates/traefik.j2') }}"

- name: Install Traefik
  uri:
    url: "https://{{ ansible_host }}:9443/api/stacks?type=2&method=file&endpointId={{ local_endpoint_id }}"
    method: POST
    return_content: true
    validate_certs: false
    headers:
      Authorization: Bearer {{ (portainer_auth.content|from_json).jwt }}
    body_format: form-multipart
    body:
      file: 
        content: "{{ traefik_yaml_contents }}"
        filename: "traefik.yml"
        content_type: "text/plain"
      Name: traefik
    status_code: 200, 409
  register: portainer_local_env

- name: Create traefik required directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ username }}/traefik"
    - "/home/{{ username }}/traefik/sites"

- name: Configure traefik sites
  template:
    src: "{{ role_path }}/templates/traefik/sites/{{ item.key }}.j2"
    dest: "/home/{{ username }}/traefik/sites/{{ item.key }}.yml"
  with_items: "{{ sites_urls | dict2items }}"

- name: Configure Traefik
  template:
    src: "{{ role_path }}/templates/traefik/traefik.j2"
    dest: "/home/{{ username }}/traefik/traefik.yml"
