- name: Update packages
  apt:
    name: "*"
    state: latest

- name: Install essential packages
  apt:
    pkg:
    - nano
    - net-tools
    - curl
    - nfs-common
    state: latest
    update_cache: yes

- name: Install QEMU Guest Agent
  apt:
    pkg:
    - qemu-guest-agent
    state: latest
  notify: Restart QEMU service

- name: Add 8.8.8.8 nameserver
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    