- name: Update packages
  apt:
    name: "*"
    state: latest

- name: Install essential packages
  apt:
    pkg:
    - nano
    - net-tools
    - curl
    - qemu-guest-agent
    state: latest
    update_cache: yes