- name: Generate password hash
  shell: >
    docker run authelia/authelia:latest authelia crypto hash generate argon2 --password '{{ authelia_password }}'
  register: hash_output

- name: Set password hash variable
  set_fact:
    authelia_password_hash: "{{ hash_output.stdout | replace('Digest: ', '') }}"

- name: Copy users config file
  template:
    src: "{{ role_path }}/templates/users.j2"
    dest: "/home/{{ username }}/authelia/users.yml"
