- name: Generate JWT_SECRET
  copy:
    content: "{{ lookup('community.general.random_string', base64=True, length=64) }}"
    dest: "/home/{{ username }}/authelia/secrets/JWT_SECRET"
  args:
    force: false

- name: Generate SESSION_SECRET
  copy:
    content: "{{ lookup('community.general.random_string', base64=True, length=64) }}"
    dest: "/home/{{ username }}/authelia/secrets/SESSION_SECRET"
  args:
    force: false

- name: Generate STORAGE_ENCRYPTION_KEY
  copy:
    content: "{{ lookup('community.general.random_string', base64=True, length=64) }}"
    dest: "/home/{{ username }}/authelia/secrets/STORAGE_ENCRYPTION_KEY"
  args:
    force: false

- name: Generate SMTP_PASSWORD
  copy:
    content: "{{ smtp_password }}"
    dest: "/home/{{ username }}/authelia/secrets/SMTP_PASSWORD"
  args:
    force: false
