- name: Pull default Docker image
  community.docker.docker_image:
    name: hello-world
    source: pull

- name: Create hello-world container
  community.docker.docker_container:
    name: hello-world
    image: hello-world
    state: present
    