- name: Create Traefik required directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ username }}/traefik"
    - "/home/{{ username }}/traefik/config"

- name: Register Home Assistant with Traefik
  template:
    src: "{{ role_path }}/templates/home_assistant.j2"
    dest: "/home/{{ username }}/traefik/config/home_assistant.yml"
