- name: Build docker-compose from template
  set_fact:
    yaml_contents: "{{ lookup('template', '{{ template_path }}') }}"

- name: Install stack
  uri:
    url: "{{ portainer_api_uri }}/stacks?type=2&method=file&endpointId={{ local_endpoint_id }}"
    method: POST
    timeout: 60
    return_content: true
    validate_certs: false
    headers:
      Authorization: Bearer {{ (portainer_auth.content|from_json).jwt }}
    body_format: form-multipart
    body:
      file: 
        content: "{{ yaml_contents }}"
        filename: "{{ stack_name }}.yml"
        content_type: "text/plain"
      Name: "{{ stack_name }}"
    status_code: 200, 409
