- name: Build Portainer API URI
  set_fact:
    portainer_api_uri: "https://{{ portainer_host }}:9443/api"

- name: Get Portainer auth token
  uri:
    url: "{{ portainer_api_uri }}/auth"
    method: POST
    return_content: true
    validate_certs: false
    body_format: json
    body: '{ "username":"{{ user }}", "password":"{{ password }}"}'
  register: portainer_auth

- name: Get environments
  uri:
    url: "{{ portainer_api_uri }}/endpoints"
    method: GET
    return_content: true
    validate_certs: false
    headers:
      Authorization: Bearer {{ (portainer_auth.content|from_json).jwt }}
  register: portainer_environments

- name: Get local endpoint
  set_fact:
    local_endpoint_id: "{{ portainer_environments.content | from_json | json_query(query) | first }}"
  vars:
    query: "[?Name=='{{ local_endpoint }}'].Id"
