- name: Update host DNS to free up port 53
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?(DNSStubListener=no)'
    line: 'DNSStubListener=no'

- name: Restart systemd-resolved to free up port 53
  systemd:
    name: systemd-resolved
    state: restarted

- name: Get Pihole docker-compose template
  set_fact:
    docker_compose_path: "{{ role_path }}/templates/docker-compose.j2"

- name: Install Pihole
  include_role:
    name: portainer_stack
  vars:
    template_path: "{{ docker_compose_path }}"
    portainer_host: "{{ ansible_host }}"
    user: "{{ portainer_user }}"
    password: "{{ portainer_password }}"
    local_endpoint: "{{ inventory_hostname }}"
    stack_name: pihole    

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ username }}/pihole"
    - "/home/{{ username }}/pihole/etc-dnsmasq.d"
    - "/home/{{ username }}/pihole/etc-pihole"
